server:
  port: ${SERVER_PORT:10020}
  tomcat:
    threads:
      max: 1025
    accept-count: 512
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/hermes
      connection-pool:
        min-size: 1
        max-size: 64
        max-wait-time: 120000  # in milliseconds
        max-connection-idle-time: 60000  # in milliseconds

kafka-config:
  operation-account:
      topic-request: "operation-account-topic-request"
      topic-process: "operation-account-topic-process"
      topic-response: "operation-account-topic-response"
      group-id: "b7f61ef6-13e7-4252-97f6-94b8ff5e8450"
